### ISSUE TITLE
Implementation issues

### ISSUE THREAD

**Issue by liyuantsao** [pf0607/COZ#1]
Thank you for your amazing work!

I am encountering some difficulties when reproducing the results with this codebase:

(1) It seems that the currently released code doesn't work as expected.
* You specify the imnet to be 'mixer-all-no_norm-sr64-localE' in the config files; however, there is no corresponding model in mlp_mixer.py. If I change it to 'MLP-mixer-all-no_norm-sr64-localE', an error indicates that the 'hidden_list' is not specified. How can I correct this to match your original implementation?
* There are some commented lines in the code. Should I just ignore them?

(2) Will you release your pre-trained checkpoints?

Thank you in advance for your help!

**Comment by pf0607** [comment]
Thank you for pointing out our mistakes. We were too hasty in uploading the code without proper check and management. We will fix the errors as soon as possible, and the checkpoints will also be released.



---- Replied Message ----
| From | Li-Yuan ***@***.***> |
| Date | 06/13/2024 09:50 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [pf0607/COZ] Implementation issues (Issue #1) |

Thank you for your amazing work!

I am encountering some difficulties when reproducing the results with this codebase:

(1) It seems that the currently released code doesn't work as expected.

You specify the imnet to be 'mixer-all-no_norm-sr64-localE' in the config files; however, there is no corresponding model in mlp_mixer.py. If I change it to 'MLP-mixer-all-no_norm-sr64-localE', an error indicates that the 'hidden_list' is not specified. How can I correct this to match your original implementation?
There are some commented lines in the code. Should I just ignore them?

(2) Will you release your pre-trained checkpoints?

Thank you in advance for your help!

**Comment by liyuantsao** [comment]
Thank you for your prompt reply and all your efforts!
